# Generated by Django 5.0.1 on 2024-03-04 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=30)),
                ('age', models.PositiveIntegerField(null=True)),
                ('address', models.CharField(default='address', max_length=40)),
                ('mobile', models.PositiveIntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('destination', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='plannerapp.destination', verbose_name='Nearby Destination')),
            ],
            options={
                'verbose_name_plural': 'Spots',
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cost_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('destination', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plannerapp.destination')),
                ('spots', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='plannerapp.spots')),
            ],
            options={
                'verbose_name_plural': 'Stays',
            },
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('destination', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plannerapp.destination', verbose_name='Nearby Destination')),
                ('spots', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='plannerapp.spots', verbose_name='Nearby Spots')),
                ('stays', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='plannerapp.stay', verbose_name='Nearby Stays')),
            ],
            options={
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=30)),
                ('age', models.PositiveIntegerField(null=True)),
                ('address', models.CharField(default='address', max_length=40)),
                ('mobile', models.PositiveIntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('total_cost', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannerapp.destination')),
                ('stays', models.ManyToManyField(to='plannerapp.stay')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannerapp.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Trips',
            },
        ),
    ]
