# Generated by Django 5.0.1 on 2024-03-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='cost_per_night',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
