# Generated by Django 5.0.1 on 2024-03-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0002_alter_stay_cost_per_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='start_date',
        ),
    ]
